services:
  frontend:
    depends_on: 
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8010/
    build: ./frontend
    ports:
      - 8001:8001
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync+restart

  # admin:
  #   depends_on: 
  #     - backend
  #   environment:
  #     - API_URL=http://localhost:8000
  #   build: ./admin
  #   ports:
  #     - 8002:8002
  #   develop:
  #     watch:
  #       - path: ./admin/package.json
  #         action: rebuild
  #       - path: ./admin/package-lock.json
  #         action: rebuild
  #       - path: ./admin
  #         target: /app
  #         action: sync

  backend:
    depends_on: 
      - db
    environment:
      - PORT=8010
      - DATABASE_URL=postgresql://rohit:secret123@db:5432/myapp
      - JWT_SECRET_KEY=hello_there_jwt_scret_see_this
      - REDIS_URL=redis://redis:6379
    build: ./backend
    ports:
      - 8010:8010
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync+restart

  fastapi:
    depends_on: 
      - db
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://rohit:secret123@db:5432/myapp
      - JWT_SECRET_KEY=hello_there_jwt_scret_see_this
      - REDIS_URL=redis://redis:6379
    build: ./fastapi-backend
    ports:
      - 8011:8000
    develop:
      watch:
        - path: ./fastapi-backend/pyproject.toml
          action: rebuild
        - path: ./fastapi-backend
          target: /app
          action: sync+restart

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: rohit
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: myapp
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - redis-data:/data
        environment:
            - REDIS_ARGS=--requirepass your_password_here --appendonly yes
        restart: unless-stopped

volumes:
  postgres_data:
  redis-data:
        driver: local

  