service: ecommerce-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET_KEY: ${env:JWT_SECRET_KEY}

plugins:
  - serverless-dotenv-plugin

build:
  esbuild:
    bundle: true
    minify: false
    platform: node
    target: node20
    format: esm
    sourcemap: true
    banner:
      js: |
        import { createRequire } from 'module';
        const require = createRequire(import.meta.url);
    external:
      - "@aws-sdk/*"

functions:
  api:
    handler: lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
